require:
  - rubocop-rspec
  - rubocop-performance

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 110
  Exclude:
    - 'lib/webdrivers/common.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/webdrivers/common.rb'

Metrics/CyclomaticComplexity:
  Max: 8

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
