AllCops:
  TargetRubyVersion: 2.4.10

require:
  - rubocop-rspec
  - rubocop-performance

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120
  IgnoredPatterns:
    - '\s+# rubocop:disable'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/ScriptPermission:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/webdrivers/tasks/*.rake'
    - 'webdrivers.gemspec'

Metrics/ClassLength:
  Max: 116
  Exclude:
    - 'lib/webdrivers/system.rb'

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/AbcSize:
  Max: 16
  Exclude:
    - 'lib/webdrivers/chromedriver.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
