sudo: required
os:
  - linux
  - osx
language: ruby
cache: bundler
rvm:
  - 2.4.1
  - jruby-9.2.0.0
addons:
  chrome: stable

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install chromium-browser libgconf-2-4 ; fi